version: '3.1'
services:
  api:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: flutter-web-test
    restart: always
    image: flutter-web-test
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["flutter", "run", "-d", "web-server", "--web-port=5001", "--profile"]